### ISSUE TITLE
Plugin version 

### ISSUE THREAD

**Issue by nealmadhu** [carbonblack/cb-response-logstash-input#3]
Team, 

I have successfully build gem file but I like to know for which version of logstash is this plugin is supported?

Also, I would like to run this Plugin with latest version of ELK stack v7? 

Looking forward to hearing from you.

Many Thanks,
Madhu

**Comment by smultani** [comment]
Neal,

This is a beta project and is unsupported. You're welcome to submit pull requests and we will review.

Thanks.
